webtalk_init -webtalk_dir C:/Users/mgaho/Vivado/PC1/servo_controller/servo_controller.sim/sim_1/behav/xsim/xsim.dir/cfg_tb_single_servo_control_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Apr 19 17:04:21 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "212965058_0_0_704" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "8baa0ab4-d288-4b40-909e-b4f1621065ec" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "37e7f1aa6604471c9989f7df7bb6ea80" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2304 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "25.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "8 ms" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "2.19_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14556_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1477116279 -regid "212965058_0_0_704" -xml C:/Users/mgaho/Vivado/PC1/servo_controller/servo_controller.sim/sim_1/behav/xsim/xsim.dir/cfg_tb_single_servo_control_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/mgaho/Vivado/PC1/servo_controller/servo_controller.sim/sim_1/behav/xsim/xsim.dir/cfg_tb_single_servo_control_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/mgaho/Vivado/PC1/servo_controller/servo_controller.sim/sim_1/behav/xsim/xsim.dir/cfg_tb_single_servo_control_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
